
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point n1[31] n1[31] -type PI PI
add mapped point n1[30] n1[30] -type PI PI
add mapped point n1[29] n1[29] -type PI PI
add mapped point n1[28] n1[28] -type PI PI
add mapped point n1[27] n1[27] -type PI PI
add mapped point n1[26] n1[26] -type PI PI
add mapped point n1[25] n1[25] -type PI PI
add mapped point n1[24] n1[24] -type PI PI
add mapped point n1[23] n1[23] -type PI PI
add mapped point n1[22] n1[22] -type PI PI
add mapped point n1[21] n1[21] -type PI PI
add mapped point n1[20] n1[20] -type PI PI
add mapped point n1[19] n1[19] -type PI PI
add mapped point n1[18] n1[18] -type PI PI
add mapped point n1[17] n1[17] -type PI PI
add mapped point n1[16] n1[16] -type PI PI
add mapped point n1[15] n1[15] -type PI PI
add mapped point n1[14] n1[14] -type PI PI
add mapped point n1[13] n1[13] -type PI PI
add mapped point n1[12] n1[12] -type PI PI
add mapped point n1[11] n1[11] -type PI PI
add mapped point n1[10] n1[10] -type PI PI
add mapped point n1[9] n1[9] -type PI PI
add mapped point n1[8] n1[8] -type PI PI
add mapped point n1[7] n1[7] -type PI PI
add mapped point n1[6] n1[6] -type PI PI
add mapped point n1[5] n1[5] -type PI PI
add mapped point n1[4] n1[4] -type PI PI
add mapped point n1[3] n1[3] -type PI PI
add mapped point n1[2] n1[2] -type PI PI
add mapped point n1[1] n1[1] -type PI PI
add mapped point n1[0] n1[0] -type PI PI
add mapped point n2[31] n2[31] -type PI PI
add mapped point n2[30] n2[30] -type PI PI
add mapped point n2[29] n2[29] -type PI PI
add mapped point n2[28] n2[28] -type PI PI
add mapped point n2[27] n2[27] -type PI PI
add mapped point n2[26] n2[26] -type PI PI
add mapped point n2[25] n2[25] -type PI PI
add mapped point n2[24] n2[24] -type PI PI
add mapped point n2[23] n2[23] -type PI PI
add mapped point n2[22] n2[22] -type PI PI
add mapped point n2[21] n2[21] -type PI PI
add mapped point n2[20] n2[20] -type PI PI
add mapped point n2[19] n2[19] -type PI PI
add mapped point n2[18] n2[18] -type PI PI
add mapped point n2[17] n2[17] -type PI PI
add mapped point n2[16] n2[16] -type PI PI
add mapped point n2[15] n2[15] -type PI PI
add mapped point n2[14] n2[14] -type PI PI
add mapped point n2[13] n2[13] -type PI PI
add mapped point n2[12] n2[12] -type PI PI
add mapped point n2[11] n2[11] -type PI PI
add mapped point n2[10] n2[10] -type PI PI
add mapped point n2[9] n2[9] -type PI PI
add mapped point n2[8] n2[8] -type PI PI
add mapped point n2[7] n2[7] -type PI PI
add mapped point n2[6] n2[6] -type PI PI
add mapped point n2[5] n2[5] -type PI PI
add mapped point n2[4] n2[4] -type PI PI
add mapped point n2[3] n2[3] -type PI PI
add mapped point n2[2] n2[2] -type PI PI
add mapped point n2[1] n2[1] -type PI PI
add mapped point n2[0] n2[0] -type PI PI

//output ports
add mapped point result[31] result[31] -type PO PO
add mapped point result[30] result[30] -type PO PO
add mapped point result[29] result[29] -type PO PO
add mapped point result[28] result[28] -type PO PO
add mapped point result[27] result[27] -type PO PO
add mapped point result[26] result[26] -type PO PO
add mapped point result[25] result[25] -type PO PO
add mapped point result[24] result[24] -type PO PO
add mapped point result[23] result[23] -type PO PO
add mapped point result[22] result[22] -type PO PO
add mapped point result[21] result[21] -type PO PO
add mapped point result[20] result[20] -type PO PO
add mapped point result[19] result[19] -type PO PO
add mapped point result[18] result[18] -type PO PO
add mapped point result[17] result[17] -type PO PO
add mapped point result[16] result[16] -type PO PO
add mapped point result[15] result[15] -type PO PO
add mapped point result[14] result[14] -type PO PO
add mapped point result[13] result[13] -type PO PO
add mapped point result[12] result[12] -type PO PO
add mapped point result[11] result[11] -type PO PO
add mapped point result[10] result[10] -type PO PO
add mapped point result[9] result[9] -type PO PO
add mapped point result[8] result[8] -type PO PO
add mapped point result[7] result[7] -type PO PO
add mapped point result[6] result[6] -type PO PO
add mapped point result[5] result[5] -type PO PO
add mapped point result[4] result[4] -type PO PO
add mapped point result[3] result[3] -type PO PO
add mapped point result[2] result[2] -type PO PO
add mapped point result[1] result[1] -type PO PO
add mapped point result[0] result[0] -type PO PO
add mapped point Overflow Overflow -type PO PO
add mapped point Underflow Underflow -type PO PO
add mapped point Exception Exception -type PO PO

//inout ports




//Sequential Pins
add mapped point Exception/q Exception_reg/Q -type DFF DFF
add mapped point Underflow/q Underflow_reg/Q -type DFF DFF
add mapped point Underflow_reg/q Underflow_reg_reg/Q -type DFF DFF
add mapped point e1_reg[0]/q e1_reg_reg[0]/Q -type DFF DFF
add mapped point e1_reg[1]/q e1_reg_reg[1]/Q -type DFF DFF
add mapped point e1_reg[2]/q e1_reg_reg[2]/Q -type DFF DFF
add mapped point e1_reg[3]/q e1_reg_reg[3]/Q -type DFF DFF
add mapped point e1_reg[4]/q e1_reg_reg[4]/Q -type DFF DFF
add mapped point e1_reg[5]/q e1_reg_reg[5]/Q -type DFF DFF
add mapped point e1_reg[6]/q e1_reg_reg[6]/Q -type DFF DFF
add mapped point e1_reg[7]/q e1_reg_reg[7]/Q -type DFF DFF
add mapped point e2_reg[0]/q e2_reg_reg[0]/Q -type DFF DFF
add mapped point e2_reg[1]/q e2_reg_reg[1]/Q -type DFF DFF
add mapped point e2_reg[2]/q e2_reg_reg[2]/Q -type DFF DFF
add mapped point e2_reg[3]/q e2_reg_reg[3]/Q -type DFF DFF
add mapped point e2_reg[4]/q e2_reg_reg[4]/Q -type DFF DFF
add mapped point e2_reg[5]/q e2_reg_reg[5]/Q -type DFF DFF
add mapped point e2_reg[6]/q e2_reg_reg[6]/Q -type DFF DFF
add mapped point e2_reg[7]/q e2_reg_reg[7]/Q -type DFF DFF
add mapped point exponent_sum_reg[0]/q exponent_sum_reg_reg[0]/Q -type DFF DFF
add mapped point exponent_sum_reg[1]/q exponent_sum_reg_reg[1]/Q -type DFF DFF
add mapped point exponent_sum_reg[2]/q exponent_sum_reg_reg[2]/Q -type DFF DFF
add mapped point exponent_sum_reg[3]/q exponent_sum_reg_reg[3]/Q -type DFF DFF
add mapped point exponent_sum_reg[4]/q exponent_sum_reg_reg[4]/Q -type DFF DFF
add mapped point exponent_sum_reg[5]/q exponent_sum_reg_reg[5]/Q -type DFF DFF
add mapped point exponent_sum_reg[6]/q exponent_sum_reg_reg[6]/Q -type DFF DFF
add mapped point exponent_sum_reg[7]/q exponent_sum_reg_reg[7]/Q -type DFF DFF
add mapped point exponent_sum_reg[8]/q exponent_sum_reg_reg[8]/Q -type DFF DFF
add mapped point final_exponent_reg[0]/q final_exponent_reg_reg[0]/Q -type DFF DFF
add mapped point final_exponent_reg[1]/q final_exponent_reg_reg[1]/Q -type DFF DFF
add mapped point final_exponent_reg[2]/q final_exponent_reg_reg[2]/Q -type DFF DFF
add mapped point final_exponent_reg[3]/q final_exponent_reg_reg[3]/Q -type DFF DFF
add mapped point final_exponent_reg[4]/q final_exponent_reg_reg[4]/Q -type DFF DFF
add mapped point final_exponent_reg[5]/q final_exponent_reg_reg[5]/Q -type DFF DFF
add mapped point final_exponent_reg[6]/q final_exponent_reg_reg[6]/Q -type DFF DFF
add mapped point final_exponent_reg[7]/q final_exponent_reg_reg[7]/Q -type DFF DFF
add mapped point m1_reg[0]/q m1_reg_reg[0]/Q -type DFF DFF
add mapped point m1_reg[1]/q m1_reg_reg[1]/Q -type DFF DFF
add mapped point m1_reg[2]/q m1_reg_reg[2]/Q -type DFF DFF
add mapped point m1_reg[3]/q m1_reg_reg[3]/Q -type DFF DFF
add mapped point m1_reg[4]/q m1_reg_reg[4]/Q -type DFF DFF
add mapped point m1_reg[5]/q m1_reg_reg[5]/Q -type DFF DFF
add mapped point m1_reg[6]/q m1_reg_reg[6]/Q -type DFF DFF
add mapped point m1_reg[7]/q m1_reg_reg[7]/Q -type DFF DFF
add mapped point m1_reg[8]/q m1_reg_reg[8]/Q -type DFF DFF
add mapped point m1_reg[9]/q m1_reg_reg[9]/Q -type DFF DFF
add mapped point m1_reg[10]/q m1_reg_reg[10]/Q -type DFF DFF
add mapped point m1_reg[11]/q m1_reg_reg[11]/Q -type DFF DFF
add mapped point m1_reg[12]/q m1_reg_reg[12]/Q -type DFF DFF
add mapped point m1_reg[13]/q m1_reg_reg[13]/Q -type DFF DFF
add mapped point m1_reg[14]/q m1_reg_reg[14]/Q -type DFF DFF
add mapped point m1_reg[15]/q m1_reg_reg[15]/Q -type DFF DFF
add mapped point m1_reg[16]/q m1_reg_reg[16]/Q -type DFF DFF
add mapped point m1_reg[17]/q m1_reg_reg[17]/Q -type DFF DFF
add mapped point m1_reg[18]/q m1_reg_reg[18]/Q -type DFF DFF
add mapped point m1_reg[19]/q m1_reg_reg[19]/Q -type DFF DFF
add mapped point m1_reg[20]/q m1_reg_reg[20]/Q -type DFF DFF
add mapped point m1_reg[21]/q m1_reg_reg[21]/Q -type DFF DFF
add mapped point m1_reg[22]/q m1_reg_reg[22]/Q -type DFF DFF
add mapped point m2_reg[0]/q m2_reg_reg[0]/Q -type DFF DFF
add mapped point m2_reg[1]/q m2_reg_reg[1]/Q -type DFF DFF
add mapped point m2_reg[2]/q m2_reg_reg[2]/Q -type DFF DFF
add mapped point m2_reg[3]/q m2_reg_reg[3]/Q -type DFF DFF
add mapped point m2_reg[4]/q m2_reg_reg[4]/Q -type DFF DFF
add mapped point m2_reg[5]/q m2_reg_reg[5]/Q -type DFF DFF
add mapped point m2_reg[6]/q m2_reg_reg[6]/Q -type DFF DFF
add mapped point m2_reg[7]/q m2_reg_reg[7]/Q -type DFF DFF
add mapped point m2_reg[8]/q m2_reg_reg[8]/Q -type DFF DFF
add mapped point m2_reg[9]/q m2_reg_reg[9]/Q -type DFF DFF
add mapped point m2_reg[10]/q m2_reg_reg[10]/Q -type DFF DFF
add mapped point m2_reg[11]/q m2_reg_reg[11]/Q -type DFF DFF
add mapped point m2_reg[12]/q m2_reg_reg[12]/Q -type DFF DFF
add mapped point m2_reg[13]/q m2_reg_reg[13]/Q -type DFF DFF
add mapped point m2_reg[14]/q m2_reg_reg[14]/Q -type DFF DFF
add mapped point m2_reg[15]/q m2_reg_reg[15]/Q -type DFF DFF
add mapped point m2_reg[16]/q m2_reg_reg[16]/Q -type DFF DFF
add mapped point m2_reg[17]/q m2_reg_reg[17]/Q -type DFF DFF
add mapped point m2_reg[18]/q m2_reg_reg[18]/Q -type DFF DFF
add mapped point m2_reg[19]/q m2_reg_reg[19]/Q -type DFF DFF
add mapped point m2_reg[20]/q m2_reg_reg[20]/Q -type DFF DFF
add mapped point m2_reg[21]/q m2_reg_reg[21]/Q -type DFF DFF
add mapped point m2_reg[22]/q m2_reg_reg[22]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[0]/q normalized_mantissa_reg_reg[0]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[1]/q normalized_mantissa_reg_reg[1]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[2]/q normalized_mantissa_reg_reg[2]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[3]/q normalized_mantissa_reg_reg[3]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[4]/q normalized_mantissa_reg_reg[4]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[5]/q normalized_mantissa_reg_reg[5]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[6]/q normalized_mantissa_reg_reg[6]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[7]/q normalized_mantissa_reg_reg[7]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[8]/q normalized_mantissa_reg_reg[8]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[9]/q normalized_mantissa_reg_reg[9]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[10]/q normalized_mantissa_reg_reg[10]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[11]/q normalized_mantissa_reg_reg[11]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[12]/q normalized_mantissa_reg_reg[12]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[13]/q normalized_mantissa_reg_reg[13]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[14]/q normalized_mantissa_reg_reg[14]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[15]/q normalized_mantissa_reg_reg[15]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[16]/q normalized_mantissa_reg_reg[16]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[17]/q normalized_mantissa_reg_reg[17]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[18]/q normalized_mantissa_reg_reg[18]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[19]/q normalized_mantissa_reg_reg[19]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[20]/q normalized_mantissa_reg_reg[20]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[21]/q normalized_mantissa_reg_reg[21]/Q -type DFF DFF
add mapped point normalized_mantissa_reg[22]/q normalized_mantissa_reg_reg[22]/Q -type DFF DFF
add mapped point raw_product_reg[23]/q raw_product_reg_reg[23]/Q -type DFF DFF
add mapped point raw_product_reg[24]/q raw_product_reg_reg[24]/Q -type DFF DFF
add mapped point raw_product_reg[25]/q raw_product_reg_reg[25]/Q -type DFF DFF
add mapped point raw_product_reg[26]/q raw_product_reg_reg[26]/Q -type DFF DFF
add mapped point raw_product_reg[27]/q raw_product_reg_reg[27]/Q -type DFF DFF
add mapped point raw_product_reg[28]/q raw_product_reg_reg[28]/Q -type DFF DFF
add mapped point raw_product_reg[29]/q raw_product_reg_reg[29]/Q -type DFF DFF
add mapped point raw_product_reg[30]/q raw_product_reg_reg[30]/Q -type DFF DFF
add mapped point raw_product_reg[31]/q raw_product_reg_reg[31]/Q -type DFF DFF
add mapped point raw_product_reg[32]/q raw_product_reg_reg[32]/Q -type DFF DFF
add mapped point raw_product_reg[33]/q raw_product_reg_reg[33]/Q -type DFF DFF
add mapped point raw_product_reg[34]/q raw_product_reg_reg[34]/Q -type DFF DFF
add mapped point raw_product_reg[35]/q raw_product_reg_reg[35]/Q -type DFF DFF
add mapped point raw_product_reg[36]/q raw_product_reg_reg[36]/Q -type DFF DFF
add mapped point raw_product_reg[37]/q raw_product_reg_reg[37]/Q -type DFF DFF
add mapped point raw_product_reg[38]/q raw_product_reg_reg[38]/Q -type DFF DFF
add mapped point raw_product_reg[39]/q raw_product_reg_reg[39]/Q -type DFF DFF
add mapped point raw_product_reg[40]/q raw_product_reg_reg[40]/Q -type DFF DFF
add mapped point raw_product_reg[41]/q raw_product_reg_reg[41]/Q -type DFF DFF
add mapped point raw_product_reg[42]/q raw_product_reg_reg[42]/Q -type DFF DFF
add mapped point raw_product_reg[43]/q raw_product_reg_reg[43]/Q -type DFF DFF
add mapped point raw_product_reg[44]/q raw_product_reg_reg[44]/Q -type DFF DFF
add mapped point raw_product_reg[45]/q raw_product_reg_reg[45]/Q -type DFF DFF
add mapped point raw_product_reg[46]/q raw_product_reg_reg[46]/Q -type DFF DFF
add mapped point raw_product_reg[47]/q raw_product_reg_reg[47]/Q -type DFF DFF
add mapped point result[0]/q result_reg[0]/Q -type DFF DFF
add mapped point result[1]/q result_reg[1]/Q -type DFF DFF
add mapped point result[2]/q result_reg[2]/Q -type DFF DFF
add mapped point result[3]/q result_reg[3]/Q -type DFF DFF
add mapped point result[4]/q result_reg[4]/Q -type DFF DFF
add mapped point result[5]/q result_reg[5]/Q -type DFF DFF
add mapped point result[6]/q result_reg[6]/Q -type DFF DFF
add mapped point result[7]/q result_reg[7]/Q -type DFF DFF
add mapped point result[8]/q result_reg[8]/Q -type DFF DFF
add mapped point result[9]/q result_reg[9]/Q -type DFF DFF
add mapped point result[10]/q result_reg[10]/Q -type DFF DFF
add mapped point result[11]/q result_reg[11]/Q -type DFF DFF
add mapped point result[12]/q result_reg[12]/Q -type DFF DFF
add mapped point result[13]/q result_reg[13]/Q -type DFF DFF
add mapped point result[14]/q result_reg[14]/Q -type DFF DFF
add mapped point result[15]/q result_reg[15]/Q -type DFF DFF
add mapped point result[16]/q result_reg[16]/Q -type DFF DFF
add mapped point result[17]/q result_reg[17]/Q -type DFF DFF
add mapped point result[18]/q result_reg[18]/Q -type DFF DFF
add mapped point result[19]/q result_reg[19]/Q -type DFF DFF
add mapped point result[20]/q result_reg[20]/Q -type DFF DFF
add mapped point result[21]/q result_reg[21]/Q -type DFF DFF
add mapped point result[22]/q result_reg[22]/Q -type DFF DFF
add mapped point result[23]/q result_reg[23]/Q -type DFF DFF
add mapped point result[24]/q result_reg[24]/Q -type DFF DFF
add mapped point result[25]/q result_reg[25]/Q -type DFF DFF
add mapped point result[26]/q result_reg[26]/Q -type DFF DFF
add mapped point result[27]/q result_reg[27]/Q -type DFF DFF
add mapped point result[28]/q result_reg[28]/Q -type DFF DFF
add mapped point result[29]/q result_reg[29]/Q -type DFF DFF
add mapped point result[30]/q result_reg[30]/Q -type DFF DFF
add mapped point result[31]/q result_reg[31]/Q -type DFF DFF
add mapped point result_sign_reg/q result_sign_reg_reg/Q -type DFF DFF
add mapped point s2_reg/q s2_reg_reg/Q -type DFF DFF
add mapped point Exception_reg/q Exception_reg_reg/Q -type DFF DFF
add mapped point s1_reg/q s1_reg_reg/Q -type DFF DFF
add mapped point m1_reg[23]/q m1_reg_reg[23]/Q -type DFF DFF
add mapped point m2_reg[23]/q m2_reg_reg[23]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
